kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "app-pipeline"
spec:
  source:
    type: "Git"
    git:
      uri: "https://github.com/mglantz/nodejs-ex.git"
  strategy:
    type: "JenkinsPipeline"
    jenkinsPipelineStrategy:
      jenkinsfilePath:
